# Generated by Django 5.1.9 on 2025-12-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reminder_on',
            field=models.BooleanField(default=False, verbose_name='是否開啟記帳提醒'),
        ),
        migrations.AddField(
            model_name='user',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True, verbose_name='提醒時間'),
        ),
    ]
